[package]
name = 'Rebase'
version = '1.2.0'
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
subdir = "aptos-framework/"
rev = "aptos-release-v1.16"

[addresses]
rebase = "_"

[dev-addresses]
rebase = "0x4000"
