[package]
name = 'Rebase'
version = '1.2.0'
upgrade_policy = "immutable"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
subdir = "aptos-move/framework/aptos-framework/"
rev = "main"

[addresses]
rebase = "_"
protocol_deployer = "0x30d13332a89b5747478a1685f88f7f4e510bca4633733d1f30c7cd60fd6fe0b4"

[dev-addresses]
rebase = "0x726562617365"
