[package]
name = 'Rebase'
version = '1.0.0'
upgrade_policy = "compatible"

[dependencies.SafeU64]
git = "https://github.com/mirage-protocol/safe_u64.git"
rev = "v1.0.0"

[addresses]
rebase = "0xdba5a1e5ec2b1e0b533720c63fd2119cd3ee347ea6bbbd1bca3306c08c8d8872"