[package]
name = 'Rebase'
version = '1.0.0'
upgrade_policy = "immutable"

[addresses]
rebase = "_"
safe_u64 = "_"

[dependencies.SafeU64]
git = "https://github.com/mirage-protocol/safe_u64.git"
rev = "main"