[package]
name = 'Rebase'
version = '1.0.1'
upgrade_policy = "compatible"

[dependencies.Safe64]
git = "https://github.com/mirage-protocol/safe_u64.git"
rev = "dev"

[addresses]
rebase = "0xf429558f9598ee1fa34eb9af4ea8cdc63b828dd0710f5f1bc435887c89099cba"